### ISSUE TITLE
Gets killed by OOM when running on Linux.

### ISSUE THREAD

**Issue by ine8181** [microsoft/DACExtensions#29]
When extracting a bacpac, it consumes a large amount of memory on the Linux and then gets killed by OOM. 

When OOM score is adjusted manually, the VM dies.

It does manage to produce a .bacpac file with model.xml, DacMetadata.xml and [Content_Types].xml. Model.xml is 10.9MB.

**Comment by pensivebrian** [comment]
This should be fixed in the [18.3.1 sqlpackage release](https://docs.microsoft.com/en-us/sql/tools/release-notes-sqlpackage?view=sql-server-2017). Prior versions were not streaming the table data, so larger tables would trigger an OOM condition. Since we now stream table data, the memory footprint should be much lower.
